name: test
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel==6.26.0
  - importlib_metadata==6.8.0
  - absl-py==2.0.0
  - asttokens==2.4.1
  - astunparse==1.6.3
  - blas==1.0=mkl
  - ca-certificates==2023.12.12
  - cachetools==5.3.2
  - certifi==2023.11.17
  - charset-normalizer==3.3.2
  - colorama==0.4.6
  - comm==0.1.4
  - contourpy==1.2.0
  - cycler==0.12.1
  - debugpy==1.6.7
  - decorator==5.1.1
  - et-xmlfile==1.1.0
  - exceptiongroup==1.2.0
  - executing==2.0.1
  - flatbuffers==23.5.26
  - fonttools==4.45.1
  - gast==0.4.0
  - google-auth==2.23.4
  - google-auth-oauthlib==0.4.6
  - google-pasta==0.2.0
  - grpcio==1.59.3
  - h5py==3.10.0
  - icc_rt==2022.1.0
  - idna==3.6
  - importlib-metadata==6.8.0
  - importlib-resources==6.1.1
  - importlib_metadata==6.8.0
  - intel-openmp==2023.1.0
  - ipykernel==6.26.0
  - ipython==8.18.1
  - jedi==0.19.1
  - joblib==1.2.0
  - jupyter_client==8.6.0
  - jupyter_core==4.12.0
  - keras==2.10.0
  - keras-preprocessing==1.1.2
  - kiwisolver==1.4.5
  - libclang==16.0.6
  - libsodium==1.0.18
  - markdown==3.5.1
  - markupsafe==2.1.3
  - matplotlib==3.8.2
  - matplotlib-inline==0.1.6

