name: mv  # Replace with your preferred environment name
channels:
  - defaults
  - conda-forge  # Add additional channels if needed
dependencies:
  - absl-py=2.0.0
  - asttokens=2.4.1
  - astunparse=1.6.3
  - blas=1.0=mkl
  - ca-certificates=2023.12.12
  - cachetools=5.3.2
  - certifi=2023.11.17
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.1.4
  - contourpy=1.2.0
  - cycler=0.12.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - flatbuffers=23.5.26
  - fonttools=4.45.1
  - gast=0.4.0
  - google-auth=2.23.4
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpcio=1.59.3
  - h5py=3.10.0
  - icc_rt=2022.1.0
  - idna=3.6
  - importlib-metadata=6.8.0
  - importlib-resources=6.1.1
  - importlib_metadata=6.8.0
  - intel-openmp=2023.1.0
  - ipykernel=6.26.0
  - ipython=8.18.1
  - jedi=0.19.1
  - joblib=1.2.0
  - jupyter_client=8.6.0
  - jupyter_core=4.12.0
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.5
  - libclang=16.0.6
  - libsodium=1.0.18
  - markdown=3.5.1
  - markupsafe=2.1.3
  - matplotlib=3.8.2
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - nest-asyncio=1.5.8
  - numpy=1.26.2
  - numpy-base=1.26.3
  - oauthlib=3.2.2
  - openpyxl=3.1.2
  - openssl=3.0.12
  - opt-einsum=3.3.0
  - packaging=23.2
  - pandas=2.1.4
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=10.1.0
  - pip=23.3.1
  - prompt-toolkit=3.0.41
  - protobuf=3.19.6
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pydot=1.4.2
  - pygments=2.17.2
  - pyparsing=3.1.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2023.3.post1
  - pywin32=227
  - pyzmq=23.2.1
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scikit-learn=1.3.0
  - scipy=1.11.4
  - seaborn=0.13.0
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tensorboard=2.10.1
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow
  - tensorflow-estimator=2.10.0
  - termcolor=2.3.0
  - threadpoolctl=2.2.0
  - tornado=6.2
  - traitlets=5.14.0
  - typing_extensions=4.8.0
  - urllib3=2.1.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.12
  - werkzeug=3.0.1
  - wheel=0.41.2
  - wrapt=1.16.0
  - zeromq=4.3.4
  - zipp=3.17.0
  - pip=23.3.1
  - python=3.9.16
